name: "prepare go"
description: this action is used to install go and set access to private go modules.

inputs:
  ACCESS_TOKEN:
    description: access token to github private repositories.
    required: true

runs:
  using: "composite"
  steps:
    - name: install go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
      with:
        go-version-file: 'go.mod'

    - name: step 2
      run: echo "this is step 2"
      shell: bash