# This workflow creates a release by creating a changelog from the
# conventional commit messages

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

name: create pre-release

jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: create changelog
        run: scripts/conventional-commits/change-log.sh > CHANGELOG.md

      - name: create pre-release
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #v7.0.1
        with:
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('CHANGELOG.md', 'utf8');

            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: '${{ github.ref_name }}',
              tag_name: '${{ github.ref_name }}',
              body: content,
              prerelease: true,
            })
