# This workflow creates a semantic version tag using conventional commits.

on:
  workflow_call:
    secrets:
      ACCESS_TOKEN:
        required: true
        description: needed to access github from the Action github-script.

name: create tag

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0 # Checkout everything to get access to the tags  

      # Automatically add semantic version tag   
      - name: get the new version
        id: semantic-version
        run: echo "version=$(scripts/conventional-commits/version.sh)" >> "$GITHUB_OUTPUT"

      - name: create tag
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #v7.0.1
        if: ${{ steps.semantic-version.outputs.version != '' }}
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.semantic-version.outputs.version }}',
              sha: context.sha
            })

