on: [push]
jobs:
    build:
        name: Hello world on push
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: print test var without passing anything.
              run: make test-step

            - name: print test var with passing it as env variable
              run: make test-step
              env:
                TEST_VAR: test-var-from-workflow-file

            - name: print test var with passing it with export
              run: export TEST_VAR="test-var-from-export-command" && make test-step

            - name: print test var with passing it two line
              run: |
                ( \
                  TEST_VAR="test var = value1" \
                  TEST_VAR1="$(make test-step)" \
                  TEST_VAR="test var = value2" \
                  TEST_VAR2="$(make test-step)" \
                  make test-step-all \
                )

                ( \
                  TEST_VAR="xxx" \
                  make test-step-all \
                )
          
        