on:
  push:
    branches: [main]
jobs:
  checking-changed-files:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          fetch-depth: $(${{ github.event.pull_request.commits }} + 1)

      - name: set output variables
        id: files_changed_step
        run: |
          {
            echo "terraform_files_changed=false"
          } >> "$GITHUB_OUTPUT"

          echo "terraform_files_changed=true" >> "$GITHUB_OUTPUT"

    outputs:
      terraform_files_changed: ${{ steps.files_changed_step.outputs.terraform_files_changed }}

  test1:
    if: needs.checking-changed-files.outputs.terraform_files_changed == 'true'
    needs: checking-changed-files
    runs-on: ubuntu-latest

    steps:
      - name: test1 step
        run: echo "test1 job - variable is true"

  test2:
    needs: checking-changed-files
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5


      - name: test step
        uses: ./.github/workflows/test1.yml
        with:
          skip_jobs: ${{ ! needs.checking-changed-files.outputs.terraform_files_changed }}

