on: [push]
jobs:
    export-dev-variables:
      name: get dev variables
      environment: dev
      runs-on: ubuntu-latest
      steps:
        - name: export dev variables for the 'docker' job
          id: export-dev-variables
          run: |-
            {
              echo "GCP_PROJECT_ID=${{ vars.GCP_PROJECT_ID }}"
              echo "GCP_SERVICE_ACCOUNT_NAME=${{ vars.GCP_SERVICE_ACCOUNT_NAME }}"
              echo "GCP_PROJECT_NUMBER=${{ vars.GCP_PROJECT_NUMBER }}"
            } >> "$GITHUB_OUTPUT"
      outputs:
        GCP_PROJECT_ID: ${{ steps.export-dev-variables.outputs.GCP_PROJECT_ID }}
        GCP_SERVICE_ACCOUNT_NAME: ${{ steps.export-dev-variables.outputs.GCP_SERVICE_ACCOUNT_NAME }}
        GCP_PROJECT_NUMBER: ${{ steps.export-dev-variables.outputs.GCP_PROJECT_NUMBER }}
    build:
        needs: export-dev-variables
        environment: dev
        name: Hello world on push
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: print test var without passing anything.
              run: make test-step

            - name: print test var with passing it as env variable
              run: make test-step
              env:
                TEST_VAR: test-var-from-workflow-file

            - name: print test var with passing it with export
              run: export TEST_VAR="test-var-from-export-command" && make test-step

            - name: print test var with passing it two line
              run: |-
                TEST_VAR="value1" \
                TEST_VAR1="$(make test-step)" \
                TEST_VAR="value2" \
                TEST_VAR2="$(make test-step)" \
                echo "var=$TEST_VAR var1=$TEST_VAR1 var2=$TEST_VAR2"

                TEST_VAR="xxx" \
                make test-step-all

            - name: tag docker image and publish to stage
              run: |-
                (
                  GCP_PROJECT_ID="${{ needs.export-dev-variables.outputs.GCP_PROJECT_ID }}"
                  DEV_IMAGE="$(make docker-info)"
                  GCP_PROJECT_ID="${{ vars.GCP_PROJECT_ID }}"
                  STAGE_IMAGE="$(make docker-info)"
                  docker tag "$DEV_IMAGE" "STAGE_IMAGE"
                )
        