on: [push]
jobs:
    build:
        name: Hello world on push
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Write a multi-line message
              run: |
                echo This demo file shows a 
                echo basic and easy-to-understand workflow.