on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'

name: on-merge-to-main

permissions:
  contents: read
  id-token: write
#  
jobs:
  Tag:
    name: Tag
    uses: ./.github/workflows/create-tag.yml
    secrets: inherit
    with:
      environment: dev