on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'

name: on-merge-to-main

  
jobs:
  Tag:
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #v7.0.1
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v0.0.2',
              sha: context.sha
            })

