on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'

name: on-merge-to-main
#  # # # # # # # #
jobs:
  Tag:
    name: Tag
    uses: ./.github/workflows/create-tag.yml
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  create-pre-release:
    needs: Tag
    uses: ./.github/workflows/create-pre-release.yml
    