on:
  push:
    branches:
      - testBranch
    tags-ignore:
      - '**'

name: on-merge-to-main
#  #
jobs:
  Tag:
    name: Tag
    uses: ./.github/workflows/create-tag.yml
    secrets: inherit
    with:
      environment: dev