on: [push]

name: on push linting code

jobs:
  gha-linting:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{github.event.pull_request.head.ref}}
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: github actions linter (info)
        id: gha-linter
        run: echo "version=$(make gha-linter-info)" >> "$GITHUB_OUTPUT"

      - name: github actions linter (cache)
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: |
            ${{ steps.gha-linter.outputs.version }}
          key: ${{ runner.os }}-gha-linter-${{ steps.gha-linter.outputs.version }}

      - name: lint github actions code
        run: make gha-lint

  conventional-commits-linting:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: ${{ github.event.pull_request.commits }}
          ref: ${{github.event.pull_request.head.ref}}
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: lint commits
        run: make conventional-commits-lint