on:
  push:
    branches: [xxx]

name: on push linting code

jobs:
  gha-linting:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{github.event.pull_request.head.ref}}

      - name: github actions linter (info)
        id: gha-linter
        run: echo "version=$(make gha-linter-info)" >> "$GITHUB_OUTPUT"

      - name: lint github actions code
        run: make gha-lint