on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

name: test workflow

jobs:
  files_changed:
    runs-on: ubuntu-latest
    #outputs:
    #  go_files_changed: ${{ steps.files_changed_step.outputs.go_files_changed }}
    #  Dockerfile_changed: ${{ steps.files_changed_step.outputs.Dockerfile_changed }}
    #  gha_changed: ${{ steps.files_changed_step.outputs.gha_changed }}
    steps:
      - name: checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{github.event.pull_request.head.ref}}
          fetch-depth: $(( ${{ github.event.pull_request.commits }}))

      - name: set ouput variables
        id: files_changed_step
        env: 
          NUMBER_OF_PR_COMMITS: ${{ github.event.pull_request.commits }}
        run: |
          echo "find the changed files in all pr commits"
          files_changed=$(git diff --name-only HEAD~$NUMBER_OF_PR_COMMITS)

          echo "go_files_changed=false" >> "$GITHUB_OUTPUT"
          echo "Dockerfile_changed=false" >> "$GITHUB_OUTPUT"
          echo "gha_changed=false" >> "$GITHUB_OUTPUT"

          if [[ $(grep "go.mod\|go.sum\|.*.go" <<< "$files_changed") ]]; then
              echo "go_files_changed=true" >> "$GITHUB_OUTPUT"
          fi

          if [[ $(grep "Dockerfile" <<< "$files_changed") ]]; then
                    echo "Dockerfile_changed=true" >> "$GITHUB_OUTPUT"
          fi

          
          if [[ $(grep ".github/workflows/" <<< "$files_changed") ]]; then
                    echo "gha_changed=true" >> "$GITHUB_OUTPUT"
          fi
          
  Print-Output:
    runs-on: ubuntu-latest
    needs: files_changed
    steps: 
      - name: print outputs
        env:
          go_files_changed: ${{ needs.files_changed.outputs.go_files_changed }}
          Dockerfile_changed: ${{ needs.files_changed.outputs.Dockerfile_changed }}
          gha_changed: ${{ needs.files_changed.outputs.gha_changed }}
        run: |
          echo "xxx $go_files_changed"
          echo "xxx $Dockerfile_changed"
          echo "xxx $gha_changed"

  Job1-go-files-changed:
    runs-on: ubuntu-latest
    needs: files_changed
    if: needs.files_changed.outputs.go_files_changed == 'true'
    steps: 
      - name: print something
        run: echo "job1 executed because go files changed"
  
  Job2-Dockerfile-changed: 
    runs-on: ubuntu-latest
    needs: files_changed
    if: needs.files_changed.outputs.Dockerfile_changed == 'true'
    steps: 
      - name: step
        run: echo "job 2 executed because dockerfile changed"


  Job3-GHA-changed: 
    runs-on: ubuntu-latest
    needs: files_changed
    if: needs.files_changed.outputs.gha_changed == 'true'
    steps: 
      - name: step
        run: echo "job 3 executed because gha changed"

