on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
      
name: PR title Linter on pull request
  
jobs:
  Go-Linting:
    runs-on: ubuntu-latest
    steps:
      - name: PR title linter
        run: ./scripts/conventional-commits/message.sh "$PR_TITLE"
        env:
          PR_TITLE: ${{ github.event.pull_request.title }} 
    
    