on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
      
name: PR title Linter on pull request
  
jobs:
  PR-Title-Linting:
    runs-on: ubuntu-latest
    steps:
        # Setup environment...
      - name: Checkout code
        uses: actions/checkout@v4 # v4.1.1

      - name: PR title linter
        run: ./scripts/conventional-commits/message.sh "$PR_TITLE"
        env:
          PR_TITLE: ${{ github.event.pull_request.title }} 
    
    