on:
  workflow_call:
    inputs:
      skip_jobs:
        description: skip all jobs in this workflow. 
        type: boolean
        required: false
        default: false

name: Run Terraform

jobs:
  run-terraform:
    if: ${{ ! inputs.skip_jobs }}
    runs-on: ubuntu-latest

    steps:
      - name: test step
        run: echo "variable skip jobs is false"