name: Go
on:
  push:
    branches: [main]

jobs:
  run-go-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: install go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: "go.mod"
      - name: private go module access
        run: |
          git config \
            --global \
            url."https://${{ secrets.ACCESS_TOKEN }}@github.com/ingka-group-digital/".insteadOf "https://github.com/ingka-group-digital/"
      - name: Build
        run: go build -v ./...
      - name: run code
        run: ./cmd/cmd