on:
  workflow_call:
    inputs:
      skip_jobs:
        description: skip all jobs in this workflow. 
        type: boolean
        required: false
        default: false

name: Run Terraform

jobs:
  run-terraform:
    if: ${{ !inputs.skip_jobs }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: test step
        run: echo "variable skip jobs is false"